function [D, S] = setProperties(D, S)
%SETPROPERTIES Sets defautlt properties
%
% D - Data
% S - Status
%

%% Data
beh = struct( ...       
            'vid', [], ...  % row 1 = frame, row 2 = currentTime of frame
            'vid_name', 'SIMIA_label_segments', ...   % default name
            'duration', 0, ...
            'default_FPS', 0, ...
            'labels', table(), ...
            'all_pos3d', [], ...
            'mod_all_pos3d', [], ...
            't_rec_dlc', []);

eeg = struct( ... 
            'temp_load', [], ...
            'nest', struct, ...
            'files', [], ...
            'flag', "", ...
            'last_val_load', [], ...
            'original', [], ... % original data
            'el_x', [], ... % electrode position x
            'el_y', [], ... % electrode position y
            'selected_pcb', [], ... % selected pcb to load (all or individual)
            'scatterPlot', [], ...
            'gridX', [], ...
            'gridY', [], ...
            'pcb_id', []);

% set
D.beh = beh;
D.eeg = eeg;


%% Status
video_analysis = struct( ...
                        'base_dir', pwd, ...
                        'idx', 0, ...
                        'max_idx', 0, ...
                        'play', false, ...
                        'fps', 10, ...
                        'start_segment', 0, ...
                        'end_segment', 0, ...
                        'dir_to_save', pwd);

kinematics = struct( ...
                    'axis_vel_only', 0 ...
                    );

nans = struct(...
             'original_lbls', [], ...
             'lbl_table', [], ...
             'num_lbls', 0, ...
             'current_lbl', 0, ...
             'lbl_segments_pos', [], ...
             'lbl_segment_vel', [], ...
             'new_signal', [], ...  # temporary interpolated signal
             'pos_or_vel', 'Position', ...
             'log', []);

neural = struct( ...
                'idx', 0,...
                'play', false,...
                'sampling_rate', 0,...
                'duration', 0, ...
                'max_idx', 0, ...
                'selected', []);

% set
S.video_analysis = video_analysis;
S.kinematics = kinematics;
S.nans = nans;
S.neural = neural;
